/* global module */
"use strict";

module.exports = {
	// "Userscript @name" : "README 3 letter designation"
	"Gist Raw Links": "grl",
	"Gist to dabblet": "g2d",
	"GitHub Code Colors": "ccr",
	"GitHub Code Folding": "cfd",
	"GitHub Code Guides": "cgl",
	"GitHub Code Show Whitespace": "csw",
	"GitHub Collapse In Comment": "cic",
	"GitHub Collapse Markdown": "cmd",
	"GitHub Copy Code Snippet": "ccs",
	"GitHub Custom Hotkeys": "chk",
	"GitHub Custom Navigation": "cnv",
	"GitHub Diff Filename": "dfn",
	"GitHub Diff Files Filter": "dff",
	"GitHub Diff Links": "dfl",
	"GitHub Files Filter": "gff",
	"GitHub Font Preview": "fpv",
	"GitHub Hide Own Feed Meta": "hof",
	"GitHub Image Preview": "ipv",
	"GitHub Indent Comment Blocks": "ioc",
	"GitHub Issue Add Details": "iad",
	"GitHub Issue Highlighter": "gih",
	"GitHub Issue Show Status": "iss",
	"GitHub Label Color Picker": "glc",
	"GitHub RTL Comment Blocks": "rtl",
	"GitHub Remove Diff Signs": "rds",
	"GitHub Reveal Header": "rhd",
	"GitHub Search Autocomplete": "sac",
	"GitHub Show Repo Issues": "ic2",
	"GitHub Sort Content": "srt",
	"GitHub Sort Reactions": "gsr",
	"GitHub Static Time": "stt",
	"GitHub TOC": "toc",
	"GitHub Title Notification": "tbn",
	"GitHub Toggle Diff Comments": "tdc",
	"GitHub Toggle Expanders": "tex",
	"GitHub Toggle Issue Comments": "ic1",
	"GitHub Toggle Wiki Sidebar": "tws",
};
